### PR TITLE
Combine "build & deploy" option with "build & deploy & provision"

### PR DESCRIPTION
**Pull request by cristianonicolai**
Update logic to the following:
If no server template is availbe, only build and deploy.
If there is only one server template, that is used by default. Select isn't shown.
Default container name is composed by GAV package plus artifact names.
If default container name is already in use, show popup for user to inpur different name.
Start container by default.
Added container name validation.
If there is more than one server template, pop up is shown to enable selection.

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@mswiderski @nmirasch please have a look.

**Comment by mswiderski** [comment]
can we use only artifactId as default container name? I believe it will be easier for users to understand that artifact is like project name while adding group to it might be too technical...

**Comment by cristianonicolai** [comment]
Yep, that makes sense to me. will update the PR.

**Comment by cristianonicolai** [comment]
@mswiderski I've updated the PR to use the artifactId, but I'm wondering if we should use the actual project name instead. WDYT?

**Comment by mswiderski** [comment]
project name can include spaces or other characters that could not be url friendly so I'd stick to artifact id to be honest

**Comment by cristianonicolai** [comment]
Fair enough.

**Pull request merged**
